KimiNoGakko/KimiNoGakko/Controllers/ClassesController.cs
using KimiNoGakko.Models;
using KimiNoGakko.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace KimiNoGakko.Controllers
{
    public class ClassesController : Controller
    {
        private readonly SchoolContext _context;

        public ClassesController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Classes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Classes.ToListAsync());
        }

        // GET: Classes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes
                .Include(c => c.Students)
                .SingleOrDefaultAsync(m => m.ClassID == id);

            if (@class == null)
            {
                return NotFound();
            }

            var vm = new ClassDetailsVM
            {
                Class = @class,
                Enrollments = await _context.Enrollments
                    .Where(x => x.ClassID == @class.ClassID)
                    .Include(x => x.Course)
                    .ToListAsync()
            };
            //ViewData["CourseItems"] = new SelectList(_context.Courses, "ID", "FullName", );

            return View(vm);
        }

        // GET: Classes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Classes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClassID,Name,Year")] Class @class)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@class);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes.SingleOrDefaultAsync(m => m.ClassID == id);
            if (@class == null)
            {
                return NotFound();
            }
            return View(@class);
        }

        // POST: Classes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClassID,Name,Year")] Class @class)
        {
            if (id != @class.ClassID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@class);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClassExists(@class.ClassID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@class);
        }

        // GET: Classes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @class = await _context.Classes
                .SingleOrDefaultAsync(m => m.ClassID == id);
            if (@class == null)
            {
                return NotFound();
            }

            return View(@class);
        }

        // POST: Classes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @class = await _context.Classes.SingleOrDefaultAsync(m => m.ClassID == id);
            _context.Classes.Remove(@class);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClassExists(int id)
        {
            return _context.Classes.Any(e => e.ClassID == id);
        }

        public IActionResult DeleteStudent(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var studentToUpdate = _context.Students.Find(id);

            if (studentToUpdate == null)
            {
                return BadRequest();
            }

            studentToUpdate.ClassID = 1;
            _context.Update(studentToUpdate);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

KimiNoGakko/KimiNoGakko/Controllers/CoursesController.cs
using KimiNoGakko.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace KimiNoGakko.Controllers
{
    public class CoursesController : Controller
    {
        private readonly SchoolContext _context;

        public CoursesController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var schoolContext = _context.Courses.Include(c => c.Employee).Include(c => c.Subject);
            return View(await schoolContext.ToListAsync());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Employee)
                .Include(c => c.Subject)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            ViewData["EmployeeItems"] = new SelectList(_context.Employees, "ID", "FullName");
            ViewData["SubjectItems"] = new SelectList(_context.Subjects, "SubjectID", "Name");
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseID,SubjectID,EmployeeID,EnrollmentID")] Course course)
        {

            var instructor = _context.Employees.Single(x => x.ID == course.EmployeeID);
            var subject = _context.Subjects.Single(x => x.SubjectID == course.SubjectID);
            if (ModelState.IsValid)
            {
                course.FullName = "[" + subject.Name + "] " + instructor.FullName;
                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeItems"] = new SelectList(_context.Employees, "ID", "FirstMidName", course.EmployeeID);
            ViewData["SubjectID"] = new SelectList(_context.Subjects, "SubjectID", "SubjectID", course.SubjectID);
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(x => x.Employee)
                .Include(x => x.Subject)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }
            ViewData["EmployeeItems"] = new SelectList(_context.Employees, "ID", "FullName", course.Employee.FullName);
            ViewData["SubjectItems"] = new SelectList(_context.Subjects, "SubjectID", "Name", course.Subject.Name);

            return View(course);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Course course)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var isntructor = _context.Employees.Find(course.EmployeeID);
                    var subject = _context.Subjects.Find(course.SubjectID);
                    //_context.Courses.Update(course);
                    course.FullName = "[" + subject.Name + "] " + isntructor.FullName;
                    _context.Entry(course).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmployeeItems"] = new SelectList(_context.Employees, "ID", "FullName", course.EmployeeID);
            ViewData["SubjectID"] = new SelectList(_context.Subjects, "SubjectID", "SubjectID", course.SubjectID);
            return View(course);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(c => c.Employee)
                .Include(c => c.Subject)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.SingleOrDefaultAsync(m => m.ID == id);
            _context.Courses.Remove(course);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.ID == id);
        }
    }
}

KimiNoGakko/KimiNoGakko/Controllers/EnrollmentsController.cs
using KimiNoGakko.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace KimiNoGakko.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly SchoolContext _context;

        public EnrollmentsController(SchoolContext context)
        {
            _context = context;
        }

        // GET: Enrollments
        public async Task<IActionResult> Index()
        {
            var schoolContext = _context.Enrollments
                    .Include(e => e.Course)
                    .Include(e => e.Class)
                    .AsNoTracking();

            return View(await schoolContext.ToListAsync());
        }

        // GET: Enrollments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Class)
                .Include(e => e.Course)
                .SingleOrDefaultAsync(m => m.ID == id);

            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // GET: Enrollments/Create
        public IActionResult Create()
        {
            ViewData["ClassItems"] = new SelectList(_context.Classes, "ClassID", "FullName");
            ViewData["CourseItems"] = new SelectList(_context.Courses, "ID", "FullName");
            return View();
        }

        // POST: Enrollments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ClassID,CourseID,ShortDescription,LongDescription")] Enrollment enrollment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(enrollment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassID"] = new SelectList(_context.Classes, "ClassID", "ClassID", enrollment.ClassID);
            ViewData["CourseID"] = new SelectList(_context.Courses, "ID", "ID", enrollment.CourseID);
            return View(enrollment);
        }

        // GET: Enrollments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(x => x.Course)
                .Include(x => x.Class)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            ViewData["ClassItems"] = new SelectList(_context.Classes, "ClassID", "FullName", enrollment.Class.FullName);
            ViewData["CourseItems"] = new SelectList(_context.Courses, "ID", "FullName", enrollment.Course.FullName);

            //ViewData["ClassID"] = new SelectList(_context.Classes, "ClassID", "FullName", enrollment.ClassID);
            //ViewData["CourseID"] = new SelectList(_context.Courses, "ID", "Name", enrollment.CourseID);
            return View(enrollment);
        }

        // POST: Enrollments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ClassID,CourseID")] Enrollment enrollment)
        {
            if (id != enrollment.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(enrollment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EnrollmentExists(enrollment.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClassID"] = new SelectList(_context.Classes, "ClassID", "ClassID", enrollment.ClassID);
            ViewData["CourseID"] = new SelectList(_context.Courses, "ID", "ID", enrollment.CourseID);
            return View(enrollment);
        }

        // GET: Enrollments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var enrollment = await _context.Enrollments
                .Include(e => e.Class)
                .Include(e => e.Course)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (enrollment == null)
            {
                return NotFound();
            }

            return View(enrollment);
        }

        // POST: Enrollments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var enrollment = await _context.Enrollments.SingleOrDefaultAsync(m => m.ID == id);
            _context.Enrollments.Remove(enrollment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EnrollmentExists(int id)
        {
            return _context.Enrollments.Any(e => e.ID == id);
        }
    }
}

KimiNoGakko/KimiNoGakko/Views/Enrollments/Create.cshtml
@model KimiNoGakko.Models.Enrollment

@{
    ViewData["Title"] = "Utwórz";
}

<h2>@ViewData["Title"]</h2>

<h4>Zapis</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Class.FullName" class="control-label"></label>
                <select asp-for="ClassID" class="form-control" asp-items="ViewBag.ClassItems"></select>
            </div>
            <div class="form-group">
                <label asp-for="Course.FullName" class="control-label"></label>
                <select asp-for="CourseID" class="form-control" asp-items="ViewBag.CourseItems"></select>
            </div>
            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription"></span>
            </div>


            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <textarea asp-for="LongDescription" class="form-control"></textarea>
                <span asp-validation-for="LongDescription"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Utwórz" class="btn btn-primary" /> |
                <a asp-action="Index">Wróć do listy</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KimiNoGakko/KimiNoGakko/Views/Enrollments/Delete.cshtml
@model KimiNoGakko.Models.Enrollment

@{
    ViewData["Title"] = "Usuń";
}

<h2>@ViewData["Title"]</h2>

<h3>Czy jesteś pewny, że chcesz usunąć zapis?</h3>
<div>
    <h4>Zapis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Class.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Class.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Course.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.FullName)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Usuń" class="btn btn-primary" /> |
        <a asp-action="Index">Wróć do listy</a>
    </form>
</div>

KimiNoGakko/KimiNoGakko/Views/Enrollments/Details.cshtml
@model KimiNoGakko.Models.Enrollment

@{
    ViewData["Title"] = "Szczegóły";
}

<h2>@ViewData["Title"]</h2>

<div>
    <h4>Zapis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Class.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Class.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Course.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Course.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>
        <dd>
            @if (Model.ShortDescription == null || Model.ShortDescription == "")
            {
                <text>(brak opisu)</text>
            }
            else
            {
                @Html.DisplayFor(model => model.ShortDescription)
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>
        <dd>
            @if (Model.LongDescription == null || Model.LongDescription == "")
            {
                <text>(brak opisu)</text>
            }
            else
            {
                @Html.DisplayFor(model => model.LongDescription)
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edytuj</a> |
    <a asp-action="Index">Wróć do listy</a>
</div>

KimiNoGakko/KimiNoGakko/Views/Enrollments/Edit.cshtml
@model KimiNoGakko.Models.Enrollment

@{
    ViewData["Title"] = "Edytuj";
}

<h2>@ViewData["Title"]</h2>

<h4>Zapis</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Class.FullName" class="control-label"></label>
                <select asp-for="ClassID" class="form-control" asp-items="ViewBag.ClassItems"></select>
                <span asp-validation-for="ClassID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Course.FullName" class="control-label"></label>
                <select asp-for="CourseID" class="form-control" asp-items="ViewBag.CourseItems"></select>
                <span asp-validation-for="CourseID" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="ShortDescription" class="control-label"></label>
                <input asp-for="ShortDescription" class="form-control" />
                <span asp-validation-for="ShortDescription"></span>
            </div>


            <div class="form-group">
                <label asp-for="LongDescription" class="control-label"></label>
                <textarea asp-for="LongDescription" class="form-control"></textarea>
                <span asp-validation-for="LongDescription"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" /> |
                <a asp-action="Index">Wróć do listy</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

KimiNoGakko/KimiNoGakko/Views/Enrollments/Index.cshtml
@model IEnumerable<KimiNoGakko.Models.Enrollment>

@{
    ViewData["Title"] = "Lista";
}

<h2>@ViewData["Title"]</h2>

<p>
    <a asp-action="Create">Utwórz zapis</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Class.FullName)
            </th>
            <th>
                Nazwa
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-controller="Classes" asp-action="Details" asp-route-id="@item.ClassID">@item.Class.FullName</a>
                </td>
                <td>
                    <a asp-controller="Courses" asp-action="Details" asp-route-id="@item.CourseID">@item.Course.FullName</a>
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edytuj</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Szczegóły</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>